Repository statechannels/go-nitro, pull requests merged in 2022-04, with the labels that each got.

#495 [nitro-protocol] fix `valid-transition.test.ts`
  nitro-protocol/test/src/valid-transition.test.ts
Labels: on-chain

#508 Update VariablePart to match off-chain code
  nitro-protocol/contracts/CountingApp.sol
  nitro-protocol/contracts/ForceMove.sol
  nitro-protocol/contracts/NitroAdjudicator.sol
  nitro-protocol/contracts/TrivialApp.sol
  nitro-protocol/contracts/examples/HashLockedSwap.sol
  nitro-protocol/contracts/examples/SingleAssetPayments.sol
  nitro-protocol/contracts/interfaces/IForceMove.sol
  nitro-protocol/contracts/interfaces/IForceMoveApp.sol
  nitro-protocol/package-lock.json
  nitro-protocol/package.json
  nitro-protocol/src/contract/challenge.ts
  nitro-protocol/src/contract/embedded-application.ts
  nitro-protocol/src/contract/force-move-app.ts
  nitro-protocol/src/contract/state.ts
  nitro-protocol/src/contract/transaction-creators/force-move.ts
  nitro-protocol/test/contracts/ForceMove/challenge.test.ts
  nitro-protocol/test/contracts/ForceMove/conclude.test.ts
  nitro-protocol/test/contracts/NitroAdjudicator/concludeAndTransferAllAssets.test.ts
  nitro-protocol/test/contracts/NitroAdjudicator/transferAllAssets.test.ts
  nitro-protocol/test/contracts/NullApp/nullApp.test.ts
  nitro-protocol/test/contracts/TrivalApp/validTransition.test.ts
  nitro-protocol/test/contracts/examples/EmbeddedApplication/validTransition.test.ts
  nitro-protocol/test/contracts/examples/HashLockedSwap/validTransition.test.ts
  nitro-protocol/test/contracts/examples/SingleAssetPayments/validTransition.test.ts
  nitro-protocol/test/test-helpers.ts
Labels: on-chain

#525 Add eslint (prettier), fix errors and warnings, run in CI
  .github/workflows/node.yml
  nitro-protocol/.eslintrc.js
  nitro-protocol/.gitignore
  nitro-protocol/.prettierrc.js
  nitro-protocol/package-lock.json
  nitro-protocol/package.json
  nitro-protocol/src/contract/challenge.ts
  nitro-protocol/src/contract/channel-storage.ts
  nitro-protocol/src/contract/channel.ts
  nitro-protocol/src/contract/embedded-application.ts
  nitro-protocol/src/contract/force-move-app.ts
  nitro-protocol/src/contract/multi-asset-holder.ts
  nitro-protocol/src/contract/state.ts
  nitro-protocol/src/contract/transaction-creators/force-move.ts
  nitro-protocol/src/contract/transaction-creators/nitro-adjudicator.ts
  nitro-protocol/src/ethers-utils.ts
  nitro-protocol/src/index.ts
  nitro-protocol/src/transactions.ts
  nitro-protocol/src/valid-transition.ts
Labels: on-chain

#536 Add linting and prettier for solidity files
  nitro-protocol/.solhint.json
  nitro-protocol/contracts/CountingApp.sol
  nitro-protocol/contracts/ForceMove.sol
  nitro-protocol/contracts/MultiAssetHolder.sol
  nitro-protocol/contracts/NitroAdjudicator.sol
  nitro-protocol/contracts/TrivialApp.sol
  nitro-protocol/contracts/examples/EmbeddedApplication.sol
  nitro-protocol/contracts/examples/HashLockedSwap.sol
  nitro-protocol/contracts/examples/SingleAssetPayments.sol
  nitro-protocol/contracts/interfaces/IStatusManager.sol
  nitro-protocol/contracts/libraries/ECRecovery.sol
  nitro-protocol/package-lock.json
  nitro-protocol/package.json
Labels: on-chain

#541 Reinstate gas benchmarks
  .github/workflows/node.yml
  nitro-protocol/gas-benchmarks/benchmark.test.ts
  nitro-protocol/gas-benchmarks/fixtures.ts
  nitro-protocol/gas-benchmarks/gas.ts
  nitro-protocol/gas-benchmarks/vanillaSetup.ts
  nitro-protocol/hardhat.config.ts
  nitro-protocol/package-lock.json
  nitro-protocol/package.json
Labels: on-chain

#547 Introduce a `_hashOutcome` on-chain helper
  nitro-protocol/contracts/ForceMove.sol
  nitro-protocol/contracts/NitroAdjudicator.sol
  nitro-protocol/gas-benchmarks/gas.ts
Labels: on-chain

#545 Introduce workflow for Go <> Solidity tests
  abi/types.go
  client/engine/chainservice/adjudicator/NitroAdjudicator.go
  client/engine/chainservice/adjudicator/challenge.go
  client/engine/chainservice/adjudicator/challenge_test.go
  client/engine/chainservice/adjudicator/doc.go
  client/engine/chainservice/adjudicator/typeconversions.go
  client/engine/chainservice/adjudicator/utils_test.go
  crypto/signatures.go
  generate-adjudicator-bindings.sh
  go.mod
  go.sum
  readme.md
Labels: on-chain

#550 Implement `_lastVariablePart` helper function
  nitro-protocol/contracts/ForceMove.sol
  nitro-protocol/gas-benchmarks/gas.ts
Labels: on-chain

#548 add action for checking bindings
  .github/workflows/bindings-check.yml
Labels: help wanted, on-chain

#560 Fix action
  .github/workflows/bindings-check.yml
  client/engine/chainservice/adjudicator/NitroAdjudicator.go
  generate-adjudicator-bindings.sh
  nitro-protocol/contracts/ForceMove.sol
  nitro-protocol/package-lock.json
  nitro-protocol/package.json
Labels: on-chain

#563 add 27 when signing, subtract when recovering
  channel/state/signedstate_test.go
  channel/state/state_test.go
  crypto/signatures.go
Labels: on-chain

#552 Bump contracts to solidity@0.7.6. Undo replacing `memory` with `calldata`
  .github/workflows/bindings-check.yml
  client/engine/chainservice/adjudicator/NitroAdjudicator.go
  nitro-protocol/.solhint.json
  nitro-protocol/contracts/CountingApp.sol
  nitro-protocol/contracts/ForceMove.sol
  nitro-protocol/contracts/MultiAssetHolder.sol
  nitro-protocol/contracts/NitroAdjudicator.sol
  nitro-protocol/contracts/StatusManager.sol
  nitro-protocol/contracts/Token.sol
  nitro-protocol/contracts/TrivialApp.sol
  nitro-protocol/contracts/examples/EmbeddedApplication.sol
  nitro-protocol/contracts/examples/HashLockedSwap.sol
  nitro-protocol/contracts/examples/SingleAssetPayments.sol
  nitro-protocol/contracts/interfaces/IForceMove.sol
  nitro-protocol/contracts/interfaces/IForceMoveApp.sol
  nitro-protocol/contracts/interfaces/IMultiAssetHolder.sol
  nitro-protocol/contracts/interfaces/IStatusManager.sol
  nitro-protocol/contracts/test/TESTForceMove.sol
  nitro-protocol/contracts/test/TESTNitroAdjudicator.sol
  nitro-protocol/gas-benchmarks/gas.ts
  nitro-protocol/hardhat.config.ts
Labels: on-chain

#577 Fix eslint errors, run eslint for all fiiles
  client/engine/chainservice/adjudicator/NitroAdjudicator.go
  nitro-protocol/.eslintrc.js
  nitro-protocol/config/jest/jest.config.js
  nitro-protocol/config/jest/jest.contracts.config.js
  nitro-protocol/config/jest/jest.gas-benchmarks.config.js
  nitro-protocol/contracts/ForceMove.sol
  nitro-protocol/contracts/examples/EmbeddedApplication.sol
  nitro-protocol/environment.d.ts
  nitro-protocol/gas-benchmarks/fixtures.ts
  nitro-protocol/gas-benchmarks/vanillaSetup.ts
  nitro-protocol/hardhat.config.ts
  nitro-protocol/jest/contract-test-setup.ts
  nitro-protocol/package.json
  nitro-protocol/scripts/postdeploy.js
  nitro-protocol/scripts/postdeploy.ts
  nitro-protocol/test/contracts/ForceMove/_acceptableWhoSignedWhat.test.ts
  nitro-protocol/test/contracts/ForceMove/_isAddressInArray.test.ts
  nitro-protocol/test/contracts/ForceMove/_validSignatures.test.ts
  nitro-protocol/test/contracts/ForceMove/challenge.test.ts
  nitro-protocol/test/contracts/ForceMove/checkpoint.test.ts
  nitro-protocol/test/contracts/ForceMove/conclude.test.ts
  nitro-protocol/test/contracts/ForceMove/requireValidInput.test.ts
  nitro-protocol/test/contracts/ForceMove/respond.test.ts
  nitro-protocol/test/contracts/ForceMove/storage.test.ts
  nitro-protocol/test/contracts/ForceMove/types.ts
  nitro-protocol/test/contracts/MultiAssetHolder/claim.test.ts
  nitro-protocol/test/contracts/MultiAssetHolder/computeClaimEffectsAndInteractions.test.ts
  nitro-protocol/test/contracts/MultiAssetHolder/computeTransferEffectsAndInteractions.test.ts
  nitro-protocol/test/contracts/MultiAssetHolder/deposit.test.ts
  nitro-protocol/test/contracts/MultiAssetHolder/isExternalDestination.test.ts
  nitro-protocol/test/contracts/MultiAssetHolder/transfer.test.ts
  nitro-protocol/test/contracts/NitroAdjudicator/concludeAndTransferAllAssets.test.ts
  nitro-protocol/test/contracts/NitroAdjudicator/transferAllAssets.test.ts
  nitro-protocol/test/contracts/NullApp/nullApp.test.ts
  nitro-protocol/test/contracts/examples/EmbeddedApplication/validTransition.test.ts
  nitro-protocol/test/contracts/examples/HashLockedSwap/validTransition.test.ts
  nitro-protocol/test/contracts/examples/SingleAssetPayments/validTransition.test.ts
  nitro-protocol/test/src/contract/encode-guarantee.test.ts
  nitro-protocol/test/src/contract/external-destination.test.ts
  nitro-protocol/test/src/contract/multi-asset-holder.test.ts
  nitro-protocol/test/src/transactions.test.ts
  nitro-protocol/test/src/valid-transition.test.ts
  nitro-protocol/test/test-helpers.ts
  nitro-protocol/webpack.config.js
Labels: on-chain

#621 refactor / doc: tidying public API godocs for publish
  channel/channel.go
  channel/consensus_channel/consensus_channel.go
  channel/consensus_channel/follower_channel.go
  channel/consensus_channel/leader_channel.go
  client/engine/store/store.go
  internal/testdata/states.go
  protocols/directdefund/directdefund.go
  protocols/directfund/directfund.go
  protocols/interfaces.go
  protocols/virtualdefund/virtualdefund.go
  protocols/virtualfund/virtualfund.go
  types/bigutils.go
  types/destination.go
  types/funds.go
  types/types.go
Labels: 📖 documentation
