Repository statechannels/go-nitro, pull requests merged in 2022-09, with the labels that each got.

#859 Add tests for `StrictTurnTaking.sol` and `Consensus.sol`
  client/engine/chainservice/adjudicator/NitroAdjudicator.go
  client/engine/chainservice/consensusapp/ConsensusApp.go
  nitro-protocol/contracts/libraries/NitroUtils.sol
  nitro-protocol/contracts/libraries/signature-logic/StrictTurnTaking.sol
  nitro-protocol/contracts/test/TESTConsensus.sol
  nitro-protocol/contracts/test/TESTNitroUtils.sol
  nitro-protocol/contracts/test/TESTStrictTurnTaking.sol
  nitro-protocol/deployment/deploy-test-contracts.ts
  nitro-protocol/environment.d.ts
  nitro-protocol/gas-benchmarks/exportBenchmarkResults.ts
  nitro-protocol/package.json
  nitro-protocol/src/bitfield-utils.ts
  nitro-protocol/src/contract/transaction-creators/revert-reasons.ts
  nitro-protocol/src/signatures.ts
  nitro-protocol/test/contracts/ConsensusApp/requireStateSupported.test.ts
  nitro-protocol/test/contracts/ForceMove/_isAddressInArray.test.ts
  nitro-protocol/test/contracts/ForceMove/challenge.test.ts
  nitro-protocol/test/contracts/ForceMove/checkpoint.test.ts
  nitro-protocol/test/contracts/ForceMove/conclude.test.ts
  nitro-protocol/test/contracts/MultiAssetHolder/isExternalDestination.test.ts
  nitro-protocol/test/contracts/NitroAdjudicator/concludeAndTransferAllAssets.test.ts
  nitro-protocol/test/contracts/NitroAdjudicator/transferAllAssets.test.ts
  nitro-protocol/test/contracts/TrivialApp/requireStateSupported.test.ts
  nitro-protocol/test/contracts/VirtualPaymentApp/requireStateSupported.test.ts
  nitro-protocol/test/contracts/examples/HashLockedSwap/requireStateSupported.test.ts
  nitro-protocol/test/contracts/examples/SingleAssetPayments/requireStateSupported.test.ts
  nitro-protocol/test/contracts/libraries/Consensus/Consensus.test.ts
  nitro-protocol/test/contracts/libraries/NitroUtils/signatures.test.ts
  nitro-protocol/test/contracts/libraries/StrictTurnTaking/StrictTurnTaking.test.ts
  nitro-protocol/test/expect-succeed.ts
  nitro-protocol/test/revert-reasons.ts
  nitro-protocol/test/src/bitfield-utils.test.ts
  nitro-protocol/test/test-helpers.ts
Labels: on-chain

#857 Clean up some comments
  nitro-protocol/contracts/VirtualPaymentApp.sol
  protocols/virtualdefund/virtualdefund.go
  protocols/virtualfund/virtualfund.go
Labels: 📖 documentation

#862 increase `solc` optimization runs by 100x in hardhat config
  nitro-protocol/gas-benchmarks/gasResults.json
  nitro-protocol/hardhat.config.ts
Labels: on-chain

#864 Refactor message format to support protocol specific messages
  client/engine/engine.go
  client/engine/messageservice/test-messageservice_test.go
  client/engine/messageservice/vectorclock_summarize_test.go
  client/engine/messageservice/vectorclock_testmessageservice.go
  client/engine/metrics.go
  client_test/virtualfund_largescale_integration_test.go
  go.mod
  go.sum
  internal/testdata/channels.go
  internal/testdata/objectives.go
  internal/testhelpers/testhelpers.go
  protocols/directdefund/directdefund.go
  protocols/directdefund/directdefund_test.go
  protocols/directfund/directfund.go
  protocols/directfund/directfund_test.go
  protocols/interfaces.go
  protocols/messages.go
  protocols/messages_test.go
  protocols/virtualdefund/virtualdefund.go
  protocols/virtualdefund/virtualdefund_test.go
  protocols/virtualfund/virtualfund.go
  protocols/virtualfund/virtualfund_single_hop_test.go
Labels: :moneybag: payments

#866 Implement virtual defunding per ADR
  client/client.go
  client/engine/engine.go
  client_test/virtualdefund_test.go
  internal/testhelpers/testhelpers.go
  payments/voucher_manager.go
  protocols/virtualdefund/serde.go
  protocols/virtualdefund/virtualdefund.go
  protocols/virtualdefund/virtualdefund_test.go
Labels: :moneybag: payments

#863 Add architectural decision record for the virtual defund protocol
  .adr/0007-virtualdefund-protocol.md
  .adr/virtual-defunding.svg
Labels: :moneybag: payments

#898 Upgrade contracts to solidity 0.8.17
  .github/workflows/bindings-check.yml
  client/engine/chainservice/adjudicator/NitroAdjudicator.go
  client/engine/chainservice/consensusapp/ConsensusApp.go
  client/engine/chainservice/erc20/Token.go
  client/engine/chainservice/virtualpaymentapp/VirtualPaymentApp.go
  generate-adjudicator-bindings.sh
  nitro-protocol/.solhint.json
  nitro-protocol/contracts/ConsensusApp.sol
  nitro-protocol/contracts/CountingApp.sol
  nitro-protocol/contracts/ForceMove.sol
  nitro-protocol/contracts/MultiAssetHolder.sol
  nitro-protocol/contracts/NitroAdjudicator.sol
  nitro-protocol/contracts/StatusManager.sol
  nitro-protocol/contracts/Token.sol
  nitro-protocol/contracts/TrivialApp.sol
  nitro-protocol/contracts/VirtualPaymentApp.sol
  nitro-protocol/contracts/examples/EmbeddedApplication.sol
  nitro-protocol/contracts/examples/HashLockedSwap.sol
  nitro-protocol/contracts/examples/SingleAssetPayments.sol
  nitro-protocol/contracts/interfaces/IForceMove.sol
  nitro-protocol/contracts/interfaces/IForceMoveApp.sol
  nitro-protocol/contracts/interfaces/IMultiAssetHolder.sol
  nitro-protocol/contracts/interfaces/INitroTypes.sol
  nitro-protocol/contracts/interfaces/IStatusManager.sol
  nitro-protocol/contracts/libraries/NitroUtils.sol
  nitro-protocol/contracts/libraries/signature-logic/Consensus.sol
  nitro-protocol/contracts/libraries/signature-logic/StrictTurnTaking.sol
  nitro-protocol/contracts/test/ShortcuttingTurnTaking.sol
  nitro-protocol/contracts/test/TESTConsensus.sol
  nitro-protocol/contracts/test/TESTForceMove.sol
  nitro-protocol/contracts/test/TESTNitroAdjudicator.sol
  nitro-protocol/contracts/test/TESTNitroUtils.sol
  nitro-protocol/contracts/test/TESTStrictTurnTaking.sol
  nitro-protocol/gas-benchmarks/gasResults.json
  nitro-protocol/hardhat.config.ts
  nitro-protocol/package-lock.json
  nitro-protocol/package.json
Labels: on-chain
