Repository statechannels/go-nitro, pull requests merged in 2023-06, with the labels that each got.

#1343 Closing go-routines ADR
  .adr/0016-closing-go-routines.md
  client/client.go
  client/engine/chainservice/eth_chainservice.go
  client/engine/engine.go
  rpc/client.go
  rpc/server.go
  rpc/transport/ws/client.go
  rpc/transport/ws/server.go
Labels: 📖 documentation

#1361 notifications: ignore vouchers when the channel has closed
  channel/virtual.go
  client/engine/engine.go
Labels: CI FLICKER🚨

#1368 Add input validation to query.GetVirtualChannel
  client/client.go
  client/query/query.go
  client_test/integration_test.go
  client_test/rpc_test.go
  rpc/client.go
  rpc/serde/jsonrpc.go
  rpc/server.go
Labels: 💣 BREAKING CHANGE
